### ISSUE TITLE
Let’s combine efforts

### ISSUE THREAD

**Issue by CodeByAlex** [hoodoo-digital/acme#50]
Hey there! Great work on this. I work on the @storybook/aem project with several other devs and we just found your project. Would you be interested in combining forces to make a really solid tool? By doing so, we wouldn’t be splitting users and the code could be in one place for others to contribute to. We look forward to hearing from you!

**Comment by madoni** [comment]
hey @CodeByAlex, thanks for reaching out! I am familiar with @storybook/aem... we're using components in this project! We'd be happy to collaborate... let me know what you have in mind. Perhaps we could have a quick call to discuss next steps.

**Comment by CodeByAlex** [comment]
Yeah I think that would be a good idea - could you join our discord channel so we can better coordinate?
